<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Moq" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Sonata.Avalonia\Sonata.Avalonia.csproj" />
        <ProjectReference Include="..\..\src\Sonata.Avalonia.Hosting\Sonata.Avalonia.Hosting.csproj" />
    </ItemGroup>
</Project>
